name: Scrape Forward

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    env:
      UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
      UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          # 移除 requirements.txt 中对 greenlet>=3.1.0 的显式声明
          pip install -r requirements.txt
          playwright install

      - name: Run scraper
        run: python main.py
